/**
 * scene-describe — Supabase Edge Function
 *
 * Accepts a base64-encoded JPEG camera frame and returns a concise,
 * accessibility-focused natural-language description generated by
 * Anthropic Claude (claude-sonnet-4-6 multimodal).
 *
 * Security:
 * - verify_jwt = true (config.toml) — caller must supply a valid
 *   Supabase JWT; the ANTHROPIC_API_KEY never leaves the server.
 * - Rate-limit: 20 requests per user per hour (tracked in-memory;
 *   for production, use a Postgres table or Redis).
 *
 * Request (POST application/json):
 *   { "image": "<base64-encoded JPEG>" }
 *
 * Response 200 (application/json):
 *   { "description": "<natural-language scene description>" }
 *
 * Error responses follow Supabase Edge Function conventions:
 *   { "error": "<message>" } with an appropriate HTTP status.
 */

import Anthropic from "npm:@anthropic-ai/sdk@0.52.0";

// ---------------------------------------------------------------------------
// Anthropic client (key read from Edge secret — never from client env)
// ---------------------------------------------------------------------------

const anthropic = new Anthropic({
  apiKey: Deno.env.get("ANTHROPIC_API_KEY") ?? "",
});

// ---------------------------------------------------------------------------
// System prompt — concise, accessibility-first descriptions
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are Aura, an AI vision assistant for Opto — a super app for blind, low-vision, and ocular-prosthesis users. Your task is to describe what you see in a camera image.

Rules:
1. Be concise — maximum 3 sentences.
2. Lead with the most important spatial or safety information (obstacles, signs, people, numbers, money).
3. Name specific objects, colors, text visible in the image (e.g., "A red traffic light showing STOP").
4. If currency or price tags are visible, read the amounts aloud.
5. If text is visible on signs, packaging, or documents, read it.
6. Avoid aesthetic commentary; focus on functional information a blind person needs.
7. Speak in plain English. End with a period.`;

// ---------------------------------------------------------------------------
// Simple in-memory rate limiter (resets on function cold start)
// ---------------------------------------------------------------------------

const userHits = new Map<string, { count: number; resetAt: number }>();

function isRateLimited(userId: string): boolean {
  const now = Date.now();
  const window = 60 * 60 * 1000; // 1 hour
  const limit = 20; // requests per window

  const entry = userHits.get(userId);
  if (!entry || now > entry.resetAt) {
    userHits.set(userId, { count: 1, resetAt: now + window });
    return false;
  }
  if (entry.count >= limit) return true;
  entry.count += 1;
  return false;
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

Deno.serve(async (req: Request): Promise<Response> => {
  // CORS pre-flight (required for Supabase Edge Functions).
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers":
          "Authorization, Content-Type, apikey",
      },
    });
  }

  if (req.method !== "POST") {
    return jsonError("Method not allowed", 405);
  }

  // ── Rate limiting ──────────────────────────────────────────────────────────
  // Extract the user's sub from the verified JWT (Supabase injects the
  // decoded payload as a request header when verify_jwt = true).
  const userId =
    req.headers.get("x-supabase-auth-sub") ?? "anonymous";
  if (isRateLimited(userId)) {
    return jsonError("Too many requests. Try again later.", 429);
  }

  // ── Parse request body ────────────────────────────────────────────────────
  let body: { image?: string };
  try {
    body = await req.json();
  } catch {
    return jsonError("Invalid JSON body.", 400);
  }

  const base64Image = body.image;
  if (!base64Image || typeof base64Image !== "string") {
    return jsonError('Missing required field "image" (base64 JPEG).', 400);
  }

  // Sanity-check the size (~1 MB base64 limit to avoid runaway costs).
  if (base64Image.length > 1_400_000) {
    return jsonError("Image too large. Compress before sending.", 413);
  }

  // ── Claude multimodal call ─────────────────────────────────────────────────
  try {
    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 256,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image",
              source: {
                type: "base64",
                media_type: "image/jpeg",
                data: base64Image,
              },
            },
            {
              type: "text",
              text: "Describe this image for a blind user.",
            },
          ],
        },
      ],
    });

    const block = message.content[0];
    if (block.type !== "text") {
      return jsonError("Unexpected response format from Claude.", 500);
    }

    return new Response(
      JSON.stringify({ description: block.text.trim() }),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      },
    );
  } catch (err) {
    console.error("[scene-describe] Claude error:", err);
    return jsonError("Scene description service unavailable.", 503);
  }
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function jsonError(message: string, status: number): Response {
  return new Response(JSON.stringify({ error: message }), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
