/**
 * scene-describe — Supabase Edge Function
 *
 * Accepts a base64-encoded JPEG camera frame (JSON body) or a multipart
 * form upload and returns a concise, accessibility-focused Bahasa Indonesia
 * scene description generated by Google Gemini 2.5 Flash-Lite.
 *
 * ## Deployment posture
 *
 * FREE PLAN (default / development):
 *   The Flutter client gates cloud calls to development builds only
 *   (VisionAiConfig.cloudSceneAllowed). Real user camera frames must NOT
 *   be sent to the free tier — Gemini's free plan trains on submitted data,
 *   which violates UU PDP for Indonesian users.
 *
 * PAID PLAN (production):
 *   Set GEMINI_API_KEY to a billing-enabled key and set
 *   SCENE_DESCRIBE_TIER=paid in the Flutter .env to lift the dev-only gate.
 *   No code change required — the swap is config-only.
 *
 * Security:
 * - verify_jwt = true (config.toml) — caller must supply a valid
 *   Supabase JWT; the GEMINI_API_KEY never leaves the server.
 * - Proxy-and-discard: the frame is processed in-memory and never
 *   written to Storage or logged (UU PDP compliance).
 * - Rate-limit: 20 requests per user per hour (in-memory; for production
 *   at scale, back this with a Postgres table or Redis).
 *
 * Environment:
 *   GEMINI_API_KEY  — required; a free or billing-enabled Gemini API key.
 *                     Use a billing-enabled key for production to avoid UU PDP
 *                     training-data concerns and quota exhaustion.
 *   SCENE_DESCRIBE_MODEL — optional; defaults to "gemini-2.5-flash-lite".
 *                          Set to swap the model without a code change.
 *
 * Request (POST application/json):
 *   { "image": "<base64-encoded JPEG>" }
 *
 * Request (POST multipart/form-data):
 *   image=<JPEG file part>
 *
 * Response 200 (application/json):
 *   { "description": "<1–2 kalimat Bahasa Indonesia>" }
 *
 * Error responses:
 *   { "error": "<message>", "code"?: "quota" } with an appropriate HTTP status.
 *   code="quota" signals Gemini or in-function quota exhaustion (HTTP 429) —
 *   the Flutter client uses this to surface a distinct spoken message.
 */

// ---------------------------------------------------------------------------
// Config — model id and API key from environment (never hardcoded)
// ---------------------------------------------------------------------------

const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY") ?? "";
const MODEL =
  Deno.env.get("SCENE_DESCRIBE_MODEL") ?? "gemini-2.5-flash-lite";

const GEMINI_URL =
  `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${GEMINI_API_KEY}`;

// ---------------------------------------------------------------------------
// System prompt — Bahasa Indonesia, concise, accessibility-first
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `Kamu adalah Aura, asisten penglihatan AI untuk Opto — aplikasi untuk pengguna tunanetra, low-vision, dan prostetik okular. Tugasmu adalah mendeskripsikan apa yang ada dalam gambar kamera.

Aturan:
1. Tulis maksimal 2 kalimat dalam Bahasa Indonesia.
2. Mulai dengan informasi yang paling penting secara spasial atau keamanan (rintangan, rambu, orang, angka, uang).
3. Sebutkan objek, warna, dan teks yang terlihat secara spesifik (misalnya: "Lampu merah menunjukkan STOP").
4. Jika ada mata uang atau label harga, sebutkan nominalnya.
5. Jika ada teks pada rambu, kemasan, atau dokumen, bacakan teksnya.
6. Hindari komentar estetik; fokus pada informasi fungsional yang dibutuhkan orang tunanetra.
7. Jangan gunakan markdown, daftar, atau simbol. Akhiri dengan tanda titik.
8. Gunakan Bahasa Indonesia saja.`;

// ---------------------------------------------------------------------------
// Simple in-memory rate limiter (resets on function cold start)
// For production at scale, replace with a Postgres-backed counter.
// ---------------------------------------------------------------------------

const userHits = new Map<string, { count: number; resetAt: number }>();

function isRateLimited(userId: string): boolean {
  const now = Date.now();
  const window = 60 * 60 * 1000; // 1 hour
  const limit = 20; // requests per window

  const entry = userHits.get(userId);
  if (!entry || now > entry.resetAt) {
    userHits.set(userId, { count: 1, resetAt: now + window });
    return false;
  }
  if (entry.count >= limit) return true;
  entry.count += 1;
  return false;
}

// ---------------------------------------------------------------------------
// Helper — extract base64 image data from the request
//
// Supports two content types:
//   application/json   → { "image": "<base64 JPEG>" }
//   multipart/form-data → image=<JPEG file part>
// ---------------------------------------------------------------------------

async function extractBase64Image(req: Request): Promise<string | null> {
  const contentType = req.headers.get("content-type") ?? "";

  if (contentType.includes("multipart/form-data")) {
    const form = await req.formData();
    const part = form.get("image");
    if (!part || typeof part === "string") return null;
    // File part → read bytes → base64-encode in-memory (proxy-and-discard)
    const bytes = new Uint8Array(await (part as File).arrayBuffer());
    return btoa(String.fromCharCode(...bytes));
  }

  // Default: application/json
  let body: { image?: string };
  try {
    body = await req.json();
  } catch {
    return null;
  }
  return body.image && typeof body.image === "string" ? body.image : null;
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

Deno.serve(async (req: Request): Promise<Response> => {
  // CORS pre-flight (required for Supabase Edge Functions).
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers":
          "Authorization, Content-Type, apikey",
      },
    });
  }

  if (req.method !== "POST") {
    return jsonError("Method not allowed", 405);
  }

  // Guard: GEMINI_API_KEY must be set (deployment check).
  if (!GEMINI_API_KEY) {
    console.error("[scene-describe] GEMINI_API_KEY secret is not set.");
    return jsonError("Scene description service is not configured.", 503);
  }

  // ── Rate limiting ──────────────────────────────────────────────────────────
  // Supabase injects the decoded JWT payload as request headers when
  // verify_jwt = true; the user's sub is available as x-supabase-auth-sub.
  const userId = req.headers.get("x-supabase-auth-sub") ?? "anonymous";
  if (isRateLimited(userId)) {
    return jsonQuotaError(
      "Batas permintaan harian deskripsi tercapai. Coba lagi besok.",
      429,
    );
  }

  // ── Extract image ──────────────────────────────────────────────────────────
  let base64Image: string | null;
  try {
    base64Image = await extractBase64Image(req);
  } catch (err) {
    console.error("[scene-describe] extractBase64Image error:", err);
    return jsonError("Permintaan tidak valid.", 400);
  }

  if (!base64Image) {
    return jsonError('Field "image" diperlukan (base64 JPEG).', 400);
  }

  // Sanity-check size (~1 MB base64 ceiling after client-side 1024px/85q compress).
  if (base64Image.length > 1_400_000) {
    return jsonError(
      "Gambar terlalu besar. Kompres sebelum mengirim.",
      413,
    );
  }

  // ── Gemini multimodal call ─────────────────────────────────────────────────
  // Proxy-and-discard: the frame is passed in-memory and never persisted.
  // Only error metadata (not frame bytes) is logged.
  try {
    const geminiRes = await fetch(GEMINI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        systemInstruction: {
          parts: [{ text: SYSTEM_PROMPT }],
        },
        contents: [
          {
            role: "user",
            parts: [
              {
                inline_data: {
                  mime_type: "image/jpeg",
                  data: base64Image,
                },
              },
              { text: "Deskripsikan gambar ini." },
            ],
          },
        ],
        generationConfig: {
          maxOutputTokens: 150,
          temperature: 0.4,
        },
      }),
    });

    if (!geminiRes.ok) {
      const errBody = await geminiRes.text();
      // Log status + first 200 chars of error body only (no frame bytes).
      console.error(
        `[scene-describe] Gemini HTTP ${geminiRes.status}:`,
        errBody.slice(0, 200),
      );
      // Map upstream Gemini 429 (quota exhaustion) to a distinct quota error
      // so the Flutter client can surface a spoken "try again tomorrow" message
      // rather than the generic offline fallback.
      if (geminiRes.status === 429) {
        return jsonQuotaError(
          "Batas kuota Gemini tercapai. Coba lagi besok. OCR masih berfungsi.",
          429,
        );
      }
      return jsonError(
        `Layanan deskripsi adegan tidak tersedia (${geminiRes.status}).`,
        502,
      );
    }

    const data = await geminiRes.json() as {
      candidates?: Array<{
        content?: { parts?: Array<{ text?: string }> };
      }>;
    };

    const description =
      data.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

    if (!description) {
      console.error("[scene-describe] Gemini returned empty candidate.");
      return jsonError(
        "Layanan deskripsi adegan mengembalikan respons kosong.",
        500,
      );
    }

    return new Response(
      JSON.stringify({ description }),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      },
    );
  } catch (err) {
    // Log the error object only — frame bytes are never in scope here.
    console.error("[scene-describe] Fetch error:", err);
    return jsonError("Layanan deskripsi adegan tidak tersedia.", 503);
  }
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function jsonError(message: string, status: number): Response {
  return new Response(JSON.stringify({ error: message }), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
    },
  });
}

/** Like jsonError but includes `"code": "quota"` so the Flutter client can
 * distinguish quota exhaustion (HTTP 429) from other server errors and surface
 * a distinct spoken Bahasa Indonesia message ("try again tomorrow"). */
function jsonQuotaError(message: string, status: number): Response {
  return new Response(JSON.stringify({ error: message, code: "quota" }), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
