// Concrete implementation of [EmergencyContactRepository].
//
// Delegates to [ProfileRemoteDataSource] for PostgREST calls and maps
// data-layer [EmergencyContactModel]s to domain [EmergencyContactEntity]s
// via the [EmergencyContactModelX.toEntity()] extension.
//
// SECURITY NOTE: `emergency_contacts` is owner-only (RLS).  The PostgREST
// layer enforces this — do not surface these records in community, map,
// or catalog surfaces.
import 'package:opto/features/profile/data/datasources/profile_remote_data_source.dart';
import 'package:opto/features/profile/data/models/emergency_contact_model_ext.dart';
import 'package:opto/features/profile/domain/entities/emergency_contact_entity.dart';
import 'package:opto/features/profile/domain/repositories/emergency_contact_repository.dart';

/// Production implementation of [EmergencyContactRepository].
///
/// Failures that escape the data source are already typed [Failure]
/// subclasses — they propagate up to the BLoC, which catches and maps
/// them to error states.
class EmergencyContactRepositoryImpl implements EmergencyContactRepository {
  const EmergencyContactRepositoryImpl({
    required ProfileRemoteDataSource remoteDataSource,
  }) : _remote = remoteDataSource;

  final ProfileRemoteDataSource _remote;

  @override
  Future<List<EmergencyContactEntity>> getContacts(String userId) async {
    final models = await _remote.getEmergencyContacts(userId);
    return models.map((m) => m.toEntity()).toList();
  }

  @override
  Future<void> addContact(EmergencyContactEntity contact) async {
    // `id` is generated by Postgres — omit it from the insert payload.
    final json = <String, dynamic>{
      'user_id': contact.userId,
      'name': contact.name,
      'phone': contact.phone,
      if (contact.relationship != null) 'relationship': contact.relationship,
      'priority': contact.priority,
    };
    await _remote.addEmergencyContact(json);
  }

  @override
  Future<void> updateContact(EmergencyContactEntity contact) async {
    // IMPORTANT 1: omit 'user_id' — it is immutable and must not appear in
    // an UPDATE payload (prevents accidental ownership transfer and RLS issues).
    final json = <String, dynamic>{
      'name': contact.name,
      'phone': contact.phone,
      'relationship': contact.relationship,
      'priority': contact.priority,
    };
    await _remote.updateEmergencyContact(contact.id, json);
  }

  @override
  Future<void> deleteContact(String contactId) async {
    await _remote.deleteEmergencyContact(contactId);
  }
}
